version: "3.5"
services:
  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    networks:
      - my-network
    ports:
      - 27017:27017

  user-authentication-service:
    container_name: user-authentication-service
    build: UserAuthentication/
    networks:
      - my-network
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
      - eurekaServer
      - cloudapiservice
    restart: always

  user-product-service:
    container_name: user-product-service
    build: UserProductService/
    networks:
      - my-network
    ports:
      - 8081:8081
    depends_on:
      - mongodbservice
      - eurekaServer
      - cloudapiservice
    restart: always
#
  cloudapiservice:
    image: cloud-api-service
    build: SpringCloudAPI/
    restart: always
    networks:
      - my-network
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaServer


  eurekaServer:
    image: eureka-service
    build: ServerEurekaApp/
    restart: always
    networks:
      - my-network
    environment:
      EUREKA_SERVER_PORT: 8761
    ports:
      - 8761:8761

networks:
  my-network:
    driver: bridge

